#cloud-config
package_upgrade: true
packages:
  - net-tools
  - iptables-persistent

runcmd:
  - sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  - sysctl -p
  - iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
  - iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
  - iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
  - iptables -t nat -A POSTROUTING -o eth0 -j SNAT --to ${snat-ip-WAN}
  - ip route add ${aks-subnet} via ${snat-ip-LAN}